services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_NAME: user
      DB_USER: ${DB_USER:-prasad89}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      - database

  database:
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db_store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-prasad89}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: user

volumes:
  db_store:
