version: "3.9"

services:
  nginx_server:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask_app

  flask_app:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  postgres_db:
    container_name: database
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db_store:/var/lib/postgresql
    environment:
      POSTGRES_USER: prasad89
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user

volumes:
  db_store:
